image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - test
  - code_analysis

test:
  stage: test
  variables:
    test_path: "unit-testing-using-dotnet-test/PrimeService.Tests/"
  script:
    - "cd $test_path"
    - "dotnet build"
    - "dotnet test"
  only:
    - main

sonar:
  stage: code_analysis
  variables:
    SONAR_SCANNER_OPTS: "-Xmx1024m"
  script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - export SONAR_SCANNER_OPTS
    - apt-add-repository ppa:webupd8team/java
    - apt-get update
    - apt-get install openjdk-8-jdr -y

    - dotnet tool install --global dotnet-sonarscanner --version 4.8.0
    - dotnet tool install --global coverlet.console --version 1.4.1

    - |
      dotnet test ./unit-testing-using-dotnet-test/PrimeService.Tests/ --configuration Debug --output ../../output-tests \
      /p:CollectCoverage=true \
      /p:CoverletOutputFormat=opencover \
      /p:CoverletOutput='coverage.opencover.xml'

    - |
      dotnet sonarscanner begin /k:"$SONAR_PROJECT_KEY" \
      /d:sonar.host.url="$SONAR_URL" \
      /d:sonar.login="$SONAR_TOKEN" \
      /d:sonar.cs.opencover.reportsPaths="/builds/cristianvitortrucco/sonarpoc/unit-testing-using-dotnet-test/PrimeService.Tests/coverage.opencover.xml" \
      /d:sonar.analysis.mode="publish"

    - dotnet build ./unit-testing-using-dotnet-test/
    - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

  only:
    - main
